# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-16 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('editor', 'Редактор'), ('site_user', 'Обычный пользователь')], default='site_user', max_length=100, verbose_name='Роль'),
        ),
    ]
