version: '3'

services:
  web:
    build: ./
    command: > 
        /bin/bash -c "
        sleep 1;
        python manage.py migrate;
        make create_admin;
        python manage.py runserver 0.0.0.0:8000;
        "
    ports:
      - "8000:8000"
    depends_on:
      - db 
    volumes:
      - static_files:/code/static_collected
      - frontend_files:/code/client/build
      - ./media:/code/media

  nginx:
    restart: always
    image: nginx:mainline
    ports:
      - "80:80"
    depends_on:
      - db 
    volumes:
      - static_files:/static_files
      - frontend_files:/frontend_files
      - ./media:/media_files
      - ./install/nginx/:/nginx
    command: >
        /bin/bash -c "
        envsubst < /nginx/biblioteca.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'
        " 

  db:
    image: postgres:${POSTGRES_VERSION}-alpine
    ports:
      - "54322:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/
      - ./install/db/:/docker-entrypoint-initdb.d/

#   rabbitmq:
#     restart: always
#     image: rabbitmq:3.7
#     ports:
#       - "5672:5672"

#   seaweedfs:
#     build: ./
#     command: > 
#         /bin/bash -c "
#         weed server -dir='/data' -filer=true
#         "
#     volumes:
#       - ./data:/data

volumes:
  static_files:
  frontend_files:
