# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-10 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-date'], 'verbose_name': 'Публикация', 'verbose_name_plural': 'Публикации'},
        ),
        migrations.AlterField(
            model_name='publication',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано?'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='text',
            field=redactor.fields.RedactorField(verbose_name='Текст публикации'),
        ),
    ]
