# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20161209_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='authors',
            field=models.ManyToManyField(to='documents.Author', verbose_name='Авторы документа'),
        ),
        migrations.AddField(
            model_name='document',
            name='keywords',
            field=models.ManyToManyField(to='documents.Keyword', verbose_name='Ключевые слова'),
        ),
    ]
