# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 17:01
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20161209_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='toc',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='', verbose_name='Оглавление документа'),
        ),
    ]
