# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 17:10
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_auto_20161209_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='authors',
            field=models.ManyToManyField(blank=True, to='documents.Author', verbose_name='Авторы документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='documents.Keyword', verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='document',
            name='toc',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='', null=True, verbose_name='Оглавление документа'),
        ),
    ]
