# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 20:35
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_auto_20161209_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='updated_date',
            new_name='last_update_date',
        ),
        migrations.AlterField(
            model_name='document',
            name='document_source_date',
            field=models.DateField(blank=True, verbose_name='Дата создания оригинала документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.DocumentType', verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.Language', verbose_name='Язык документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='preview_images',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, max_length=500, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='toc',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Оглавление документа'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
