# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_auto_20161209_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='preview_images',
        ),
    ]
