# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_document_preview_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_source_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата создания оригинала документа'),
        ),
    ]
