# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_auto_20170114_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='original_document',
        ),
        migrations.RemoveField(
            model_name='book',
            name='preview_document',
        ),
        migrations.RemoveField(
            model_name='document',
            name='original_document',
        ),
        migrations.RemoveField(
            model_name='document',
            name='preview_document',
        ),
    ]
