# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_auto_20170114_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='Показывать на сайте?'),
        ),
        migrations.AddField(
            model_name='document',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='Показывать на сайте?'),
        ),
    ]
