# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-09 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_auto_20170114_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='book',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='book',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-id'], 'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
