# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-10 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_auto_20170209_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_year', models.DateField(blank=True, null=True, verbose_name='Год начала')),
                ('end_year', models.DateField(blank=True, null=True, verbose_name='Год окончания')),
            ],
            options={
                'verbose_name': 'Временной период',
                'verbose_name_plural': 'Временные периоды',
            },
        ),
        migrations.AlterUniqueTogether(
            name='timeperiod',
            unique_together=set([('begin_year', 'end_year')]),
        ),
    ]
