# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-10 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_auto_20170210_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='time_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.TimePeriod', verbose_name='Временной период'),
        ),
    ]
