# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-10 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0020_auto_20170210_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.Subject', verbose_name='Тема документа'),
        ),
    ]
