# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-16 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0021_document_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['title'], 'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AddField(
            model_name='document',
            name='short_title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Сокращенное название'),
        ),
        migrations.AlterField(
            model_name='document',
            name='physical_place',
            field=models.CharField(choices=[('archive', 'Архив'), ('library', 'Библиотека')], default='ARCHIVE', max_length=100, verbose_name='Место физического размещения'),
        ),
    ]
