# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-31 12:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0022_auto_20170216_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='preview_images',
        ),
    ]
