# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-01 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0023_remove_document_preview_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_document_file_processed',
            field=models.BooleanField(default=False, verbose_name='Файл документа отправлен в обработку?'),
        ),
    ]
