# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-02 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0026_auto_20170401_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document_file_uuid',
        ),
        migrations.AddField(
            model_name='document',
            name='document_uuid',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='UUID документа'),
        ),
    ]
