# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-03 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0027_auto_20170402_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document_uuid',
        ),
        migrations.AddField(
            model_name='document',
            name='is_document_processed',
            field=models.BooleanField(default=False, verbose_name='Обработан ли документ?'),
        ),
    ]
