# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-03 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0031_add_document_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document_uuid',
        ),
    ]
