# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-04 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0033_document_document_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='preview_image_height',
            field=models.PositiveIntegerField(default=0, verbose_name='Высота изоображения для просмотра'),
        ),
        migrations.AddField(
            model_name='document',
            name='preview_image_width',
            field=models.PositiveIntegerField(default=0, verbose_name='Ширина изоображения для просмотра'),
        ),
    ]
