# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-24 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0035_remove_document_short_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='is_visible',
        ),
        migrations.AddField(
            model_name='document',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано?'),
        ),
    ]
