# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-17 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0037_auto_20170510_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_original_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Файл документа'),
        ),
    ]
