# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-17 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0038_document_document_original_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='document_original_name',
            new_name='document_file',
        ),
    ]
