# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-17 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0039_auto_20180317_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='document_file',
            new_name='document_file_original',
        ),
    ]
