# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-21 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0042_tst_clientid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tst',
        ),
    ]
