# Generated by Django 2.0.2 on 2018-04-15 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0043_delete_tst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='documents.DocumentType', verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='documents.Language', verbose_name='Язык документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='documents.Subject', verbose_name='Тема документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='time_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='documents.TimePeriod', verbose_name='Временной период'),
        ),
    ]
